// Thin re-export of the on-chain constants the MCP tools need — single source of truth is src/config.ts.
export {
  ARC,
  IDENTITY_REGISTRY_ADDRESS, IDENTITY_REGISTRY_ABI,
  AGENT_JOBS_ADDRESS, AGENT_JOBS_ABI,
  AGENT_PAY_V3_VAULT_ABI, AGENT_PAY_V3_FACTORY_ADDRESS, AGENT_PAY_V3_FACTORY_ABI,
  REPUTATION_REGISTRY_ADDRESS, REPUTATION_REGISTRY_ABI,
  VALIDATION_REGISTRY_ADDRESS, VALIDATION_REGISTRY_ABI,
  ARC_PAY_ADDRESS,
} from "../../src/config";
