import {useCallback,useEffect,useMemo,useState} from "react";
import {BrowserProvider,Contract,JsonRpcProvider,ZeroAddress,formatEther,id,isAddress,parseEther} from "ethers";
import {AGENT_PAY_ADDRESS,AGENT_PAY_FACTORY_ADDRESS,ARC,IDENTITY_REGISTRY_ADDRESS,IDENTITY_REGISTRY_ABI,AGENT_PASSPORT_ADDRESS,AGENT_PASSPORT_ABI,AGENT_PAY_V3_VAULT_ABI,AGENT_METADATA_ENDPOINT} from "../config";
import "./AgentPay.css";

const VAULT_ABI=["function owner() view returns(address)","function policies(address) view returns(uint128 perPayment,uint128 dailyLimit,uint128 spentToday,uint64 validUntil,uint32 spendDay,bool enabled)","function merchantAllowed(address,address) view returns(bool)","function setPolicy(address,uint128,uint128,uint64,bool)","function setMerchant(address,address,bool)","function payInvoice(bytes32,address,uint256,uint64,bytes32)","function withdraw(address,uint256)"];
const FACTORY_ABI=["function arcPay() view returns(address)","function vaultOf(address) view returns(address)","function vaultCount() view returns(uint256)","function createVault() payable returns(address)"];
type Props={account:string;chainId:number|null;activeProvider:EthereumProvider|null;connect:()=>void};
const short=(x:string)=>x?`${x.slice(0,6)}…${x.slice(-4)}`:"—";

export default function AgentPay({account,chainId,activeProvider,connect}:Props){
 const [ownerVault,setOwnerVault]=useState("");const [executionVault,setExecutionVault]=useState("");const [balance,setBalance]=useState("0");const [vaultCount,setVaultCount]=useState(0);const [agent,setAgent]=useState("");const [merchant,setMerchant]=useState("");const [perPay,setPerPay]=useState("0.25");const [daily,setDaily]=useState("1");const [days,setDays]=useState("7");const [invoice,setInvoice]=useState("");const [amount,setAmount]=useState("");const [memo,setMemo]=useState("");const [initialFunding,setInitialFunding]=useState("0");const [withdrawAmount,setWithdrawAmount]=useState("");const [status,setStatus]=useState("");const [busy,setBusy]=useState(false);const [policy,setPolicy]=useState<any>(null);
 const [index,setIndex]=useState<any>(null);
 const [agentName,setAgentName]=useState("");const [agentDesc,setAgentDesc]=useState("");const [agentImage,setAgentImage]=useState("");const [agentCaps,setAgentCaps]=useState("payments");const [agentModes,setAgentModes]=useState("arcpay");const [newAgentId,setNewAgentId]=useState("");const [bindAgentId,setBindAgentId]=useState("");const [bindWalletAddr,setBindWalletAddr]=useState("");
 const selectedVault=executionVault||ownerVault;const isVaultOwner=Boolean(ownerVault&&selectedVault.toLowerCase()===ownerVault.toLowerCase());
 const refresh=useCallback(async()=>{if(!AGENT_PAY_FACTORY_ADDRESS)return;const p=new JsonRpcProvider(ARC.rpc,undefined,{batchMaxCount:1});try{const f=new Contract(AGENT_PAY_FACTORY_ADDRESS,FACTORY_ABI,p);setVaultCount(Number(await f.vaultCount()));let own="";if(account){const v=await f.vaultOf(account);if(v!==ZeroAddress){own=v;setOwnerVault(v);setExecutionVault(x=>x||v)}}if(selectedVault&&isAddress(selectedVault)){setBalance(formatEther(await p.getBalance(selectedVault)));const row=await new Contract(selectedVault,VAULT_ABI,p).policies(account);setPolicy({perPay:formatEther(row.perPayment),daily:formatEther(row.dailyLimit),spent:formatEther(row.spentToday),validUntil:Number(row.validUntil),enabled:row.enabled})}else if(!own){setBalance("0");setPolicy(null)}}finally{p.destroy()}},[account,selectedVault]);
 useEffect(()=>{void refresh()},[refresh]);
 useEffect(()=>{fetch("/data/agentpay-index.json",{cache:"no-store"}).then(r=>r.ok?r.json():null).then(setIndex).catch(()=>{})},[status]);
 async function signer(){if(!activeProvider){connect();throw Error("Connect wallet first")}if(chainId!==ARC.id){await activeProvider.request({method:"wallet_switchEthereumChain",params:[{chainId:ARC.hexId}]});throw Error("Network switched. Review and submit again.")}return new BrowserProvider(activeProvider).getSigner()}
 async function submit(label:string,target:string,abi:string[],fn:(c:Contract,s:any)=>Promise<any>){setBusy(true);setStatus(`${label}: waiting for wallet…`);try{const s=await signer();const tx=await fn(new Contract(target,abi,s),s);setStatus(`${label} submitted ${short(tx.hash)}…`);await tx.wait();setStatus(`${label} confirmed ${tx.hash}`);await refresh()}catch(e){setStatus(e instanceof Error?e.message:"Action failed")}finally{setBusy(false)}}
 async function registerPassport(){setBusy(true);setStatus("Passport: pinning metadata to IPFS…");try{
  const meta={name:agentName,description:agentDesc,image:agentImage,version:"1",capabilities:agentCaps.split(",").map(s=>s.trim()).filter(Boolean),supportedPaymentModes:agentModes.split(",").map(s=>s.trim()).filter(Boolean)};
  const res=await fetch(AGENT_METADATA_ENDPOINT,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(meta)});
  if(!res.ok)throw Error("Metadata pin failed");
  const {url}=await res.json();if(!url)throw Error("No metadata URI returned");
  const s=await signer();const reg=new Contract(IDENTITY_REGISTRY_ADDRESS,IDENTITY_REGISTRY_ABI,s);
  setStatus("Passport: waiting for wallet…");const tx=await reg.register(url);setStatus(`Registering ${short(tx.hash)}…`);const rc=await tx.wait();
  const mint=rc.logs.map((l:any)=>{try{return reg.interface.parseLog(l)}catch{return null}}).find((e:any)=>e&&e.name==="Transfer"&&e.args.from===ZeroAddress);
  const aid=mint?mint.args.tokenId.toString():"";setNewAgentId(aid);setBindAgentId(aid);setStatus(`Passport registered — Agent ID ${aid} · ${url}`)
 }catch(e){setStatus(e instanceof Error?e.message:"Registration failed")}finally{setBusy(false)}}
 const bindAgentWallet=()=>submit("Bind wallet",AGENT_PASSPORT_ADDRESS,AGENT_PASSPORT_ABI,c=>c.bindWallet(BigInt(bindAgentId),bindWalletAddr));
 const invoiceId=useMemo(()=>/^0x[0-9a-fA-F]{64}$/.test(invoice)?invoice:id(`${selectedVault}:${merchant}:${invoice}`),[invoice,merchant,selectedVault]);
 const create=()=>submit("Vault creation",AGENT_PAY_FACTORY_ADDRESS,FACTORY_ABI,c=>c.createVault({value:parseEther(initialFunding||"0")}));
 const indexedVault=index?.vaults?.find((v:any)=>v.vault.toLowerCase()===selectedVault.toLowerCase());
 return <main className="agent-pay"><header><p>AGENT PAY V2 · SELF-SERVICE</p><h1>Your funds.<br/>Your agents. Your limits.</h1><span>Every user creates an isolated non-custodial vault, then authorizes agents and merchants under contract-enforced spending limits.</span><div><b>LIVE FACTORY</b><a href={`${ARC.explorer}/address/${AGENT_PAY_FACTORY_ADDRESS}`} target="_blank" rel="noreferrer">{short(AGENT_PAY_FACTORY_ADDRESS)} ↗</a></div></header>
 <section className="agent-metrics"><article><small>PUBLIC VAULTS</small><strong>{vaultCount}</strong></article><article><small>MY VAULT</small><strong>{short(ownerVault)}</strong></article><article><small>SELECTED BALANCE</small><strong>{Number(balance).toFixed(4)} USDC</strong></article><article><small>ROLE</small><strong>{isVaultOwner?"VAULT OWNER":policy?.enabled?"ACTIVE AGENT":"READ ONLY"}</strong></article></section>
 {!account?<button className="agent-connect" onClick={connect}>Connect wallet</button>:<>
 {!ownerVault&&<section className="agent-onboard"><p>STEP 1 · CREATE YOUR VAULT</p><h2>One isolated vault for this wallet</h2><span>Your connected wallet becomes immutable owner. Arcodian cannot configure agents or withdraw its funds.</span><label>Optional initial funding<input value={initialFunding} onChange={e=>setInitialFunding(e.target.value)} placeholder="0"/></label><button disabled={busy} onClick={()=>void create()}>Create my Agent Pay vault</button></section>}
 <section className="agent-identity"><p>AGENT PASSPORT · ERC-8004</p><h2>Register an on-chain agent identity</h2><span>Mint an official ERC-8004 identity, then bind the wallet allowed to spend under it. Identity alone grants no spending authority — a v3 vault policy must also exist.</span><label>Name<input value={agentName} onChange={e=>setAgentName(e.target.value)} placeholder="My settlement agent"/></label><label>Description<input value={agentDesc} onChange={e=>setAgentDesc(e.target.value)} placeholder="What this agent does"/></label><label>Image URL<input value={agentImage} onChange={e=>setAgentImage(e.target.value)} placeholder="https://…"/></label><div className="agent-row"><label>Capabilities<input value={agentCaps} onChange={e=>setAgentCaps(e.target.value)} placeholder="payments,invoicing"/></label><label>Payment modes<input value={agentModes} onChange={e=>setAgentModes(e.target.value)} placeholder="arcpay"/></label></div><button disabled={busy||!agentName} onClick={()=>void registerPassport()}>Register passport</button>{newAgentId&&<aside>Agent ID <b>{newAgentId}</b> — <a href={`/agent/${newAgentId}`}>view profile ↗</a></aside>}<h3>Bind authorized wallet</h3><div className="agent-row"><label>Agent ID<input value={bindAgentId} onChange={e=>setBindAgentId(e.target.value)} placeholder="7"/></label><label>Wallet<input value={bindWalletAddr} onChange={e=>setBindWalletAddr(e.target.value)} placeholder="0x…"/></label></div><button disabled={busy||!bindAgentId||!isAddress(bindWalletAddr)} onClick={()=>void bindAgentWallet()}>Bind / rotate wallet</button></section>
 <label>Vault used for execution<input value={executionVault} onChange={e=>setExecutionVault(e.target.value)} placeholder="Your vault or a vault that authorized this agent"/></label>
 {selectedVault&&<div className="agent-grid">{isVaultOwner&&<section><p>OWNER CONTROLS</p><h2>Configure this vault</h2><label>Agent address<input value={agent} onChange={e=>setAgent(e.target.value)} placeholder="0x…"/></label><div className="agent-row"><label>Per payment<input value={perPay} onChange={e=>setPerPay(e.target.value)}/></label><label>Daily cap<input value={daily} onChange={e=>setDaily(e.target.value)}/></label><label>Valid days<input value={days} onChange={e=>setDays(e.target.value)}/></label></div><button disabled={busy||!isAddress(agent)} onClick={()=>void submit("Policy",selectedVault,VAULT_ABI,c=>c.setPolicy(agent,parseEther(perPay),parseEther(daily),Math.floor(Date.now()/1000)+Number(days)*86400,true))}>Set bounded policy</button><button disabled={busy||!isAddress(agent)} onClick={()=>void submit("Agent pause",selectedVault,VAULT_ABI,c=>c.setPolicy(agent,parseEther(perPay),parseEther(daily),Math.floor(Date.now()/1000)+Number(days)*86400,false))}>Pause agent</button><label>Identity policy Agent ID (v3 vault)<input value={bindAgentId} onChange={e=>setBindAgentId(e.target.value)} placeholder="7"/></label><button disabled={busy||!bindAgentId} onClick={()=>void submit("Identity policy",selectedVault,AGENT_PAY_V3_VAULT_ABI,c=>c.setPolicy(BigInt(bindAgentId),parseEther(perPay),parseEther(daily),Math.floor(Date.now()/1000)+Number(days)*86400,true))}>Set identity-bound policy (v3)</button><label>Merchant<input value={merchant} onChange={e=>setMerchant(e.target.value)} placeholder="0x…"/></label><button disabled={busy||!isAddress(agent)||!isAddress(merchant)} onClick={()=>void submit("Merchant permission",selectedVault,VAULT_ABI,c=>c.setMerchant(agent,merchant,true))}>Allow merchant</button><button disabled={busy||!amount} onClick={()=>void submit("Fund vault",selectedVault,VAULT_ABI,(_c,s)=>s.sendTransaction({to:selectedVault,value:parseEther(amount)}))}>Fund {amount||"0"} USDC</button><label>Withdraw amount<input value={withdrawAmount} onChange={e=>setWithdrawAmount(e.target.value)} placeholder="0"/></label><button disabled={busy||!withdrawAmount} onClick={()=>void submit("Owner withdrawal",selectedVault,VAULT_ABI,c=>c.withdraw(account,parseEther(withdrawAmount)))}>Withdraw to owner</button></section>}
 <section><p>AGENT EXECUTION</p><h2>Settle an Arc Pay invoice</h2>{policy&&<aside><b>{policy.enabled?"Policy active":"No active policy"}</b><span>{policy.spent} / {policy.daily} USDC spent today · {policy.perPay} max each</span><small>Expires {policy.validUntil?new Date(policy.validUntil*1000).toLocaleString():"—"}</small></aside>}<label>Merchant<input value={merchant} onChange={e=>setMerchant(e.target.value)} placeholder="0x…"/></label><label>Invoice ID / order reference<input value={invoice} onChange={e=>setInvoice(e.target.value)} placeholder="ORDER-2048 or 0x…"/></label><label>Amount<input value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0.00"/></label><label>Memo<input value={memo} onChange={e=>setMemo(e.target.value)} placeholder="Optional reconciliation memo"/></label><button disabled={busy||!isAddress(merchant)||!invoice||!amount||!policy?.enabled} onClick={()=>void submit("Agent payment",selectedVault,VAULT_ABI,c=>c.payInvoice(invoiceId,merchant,parseEther(amount),Math.floor(Date.now()/1000)+3600,id(memo||invoice)))}>Pay bounded invoice</button><code>{invoiceId}</code></section></div>}</>}
 {indexedVault&&<section className="agent-activity"><p>ONCHAIN VAULT ACTIVITY</p><h2>Policies, permissions, and receipts</h2><div className="agent-metrics"><article><small>AGENTS</small><strong>{indexedVault.policies.length}</strong></article><article><small>MERCHANT RULES</small><strong>{indexedVault.permissions.filter((x:any)=>x.allowed).length}</strong></article><article><small>ACTIVITY</small><strong>{indexedVault.activity.length}</strong></article><article><small>INDEXED BLOCK</small><strong>{index.indexedBlock}</strong></article></div>{indexedVault.policies.map((p:any)=><aside key={p.agent}><b>{short(p.agent)} · {p.enabled?"ACTIVE":"PAUSED"}</b><span>{p.perPayment} each · {p.dailyLimit} daily</span><small>Expires {new Date(p.validUntil*1000).toLocaleString()}</small></aside>)}{indexedVault.permissions.filter((x:any)=>x.allowed).map((x:any)=><p key={`${x.agent}:${x.merchant}`}>Merchant {short(x.merchant)} allowed for {short(x.agent)}</p>)}{indexedVault.activity.map((x:any)=><p key={x.tx}><a href={`${ARC.explorer}/tx/${x.tx}`} target="_blank" rel="noreferrer">{x.type.toUpperCase()} · {x.amount} USDC · {short(x.tx)} ↗</a></p>)}<a href="/agentpay-sdk.mjs" target="_blank" rel="noreferrer">Open agent integration kit →</a></section>}
 {status&&<p className="agent-status">{status}</p>}<footer><span>Factory creates isolated immutable-owner vaults. Legacy treasury vault remains at {short(AGENT_PAY_ADDRESS)}.</span><a href="/arcpay">Arc Pay receipts →</a></footer></main>}
